config/routes.rb
Rails.application.routes.draw do
  root 'zebra#index'
  resources :zebras

end

app/models/zebra.rb
class Zebra < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/zebras_controller.rb
class ZebrasController < ApplicationController
  before_action :set_zebra, only: [:show, :edit, :update, :destroy]

  # GET /zebras
  # GET /zebras.json
  def index
    @zebras = Zebra.all
  end

  # GET /zebras/1
  # GET /zebras/1.json
  def show
  end

  # GET /zebras/new
  def new
    @zebra = Zebra.new
  end

  # GET /zebras/1/edit
  def edit
  end

  # POST /zebras
  # POST /zebras.json
  def create
    @zebra = Zebra.new(zebra_params)

    respond_to do |format|
      if @zebra.save
        format.html { redirect_to @zebra, notice: 'Zebra was successfully created.' }
        format.json { render :show, status: :created, location: @zebra }
      else
        format.html { render :new }
        format.json { render json: @zebra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zebras/1
  # PATCH/PUT /zebras/1.json
  def update
    respond_to do |format|
      if @zebra.update(zebra_params)
        format.html { redirect_to @zebra, notice: 'Zebra was successfully updated.' }
        format.json { render :show, status: :ok, location: @zebra }
      else
        format.html { render :edit }
        format.json { render json: @zebra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zebras/1
  # DELETE /zebras/1.json
  def destroy
    @zebra.destroy
    respond_to do |format|
      format.html { redirect_to zebras_url, notice: 'Zebra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zebra
      @zebra = Zebra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zebra_params
      params.require(:zebra).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zebras_helper.rb
module ZebrasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SomeRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zebras/_form.html.erb
<%= form_for(@zebra) do |f| %>
  <% if @zebra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zebra.errors.count, "error") %> prohibited this zebra from being saved:</h2>

      <ul>
      <% @zebra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zebras/edit.html.erb
<h1>Editing Zebra</h1>

<%= render 'form' %>

<%= link_to 'Show', @zebra %> |
<%= link_to 'Back', zebras_path %>

app/views/zebras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Zebras</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zebras.each do |zebra| %>
      <tr>
        <td><%= zebra.name %></td>
        <td><%= link_to 'Show', zebra %></td>
        <td><%= link_to 'Edit', edit_zebra_path(zebra) %></td>
        <td><%= link_to 'Destroy', zebra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zebra', new_zebra_path %>

app/views/zebras/new.html.erb
<h1>New Zebra</h1>

<%= render 'form' %>

<%= link_to 'Back', zebras_path %>

app/views/zebras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zebra.name %>
</p>

<%= link_to 'Edit', edit_zebra_path(@zebra) %> |
<%= link_to 'Back', zebras_path %>